# golangci-lint configuration for Go MCP Library
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be noisy for structs
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  goimports:
    local-prefixes: github.com/dhirajsb/gomcp
  
  golint:
    min-confidence: 0
  
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 0,1,2,3,4,5,10,100,1000
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional useful linters
    - bodyclose
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - lll
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
    
    # Performance
    - prealloc

issues:
  exclude-use-default: false
  exclude-rules:
    # Ignore missing comments for exported functions in test files
    - path: _test\.go
      linters:
        - revive
        - golint
    
    # Ignore line length in generated files
    - path: \.pb\.go$
      linters:
        - lll
    
    # Ignore magic numbers in tests
    - path: _test\.go
      linters:
        - gomnd
    
    # Ignore specific issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    - text: "should have a package comment"
      linters:
        - revive
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true